# Generated by Django 5.2.14 on 2026-05-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_spontaneous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='meeting_point',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.category'),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
