# Generated by Django 5.2.14 on 2026-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_favoriteexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
