# Generated by Django 5.2.14 on 2026-05-29 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_max_participants_and_more'),
        ('reviews', '0002_alter_review_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'experience'), name='unique_user_experience_review'),
        ),
    ]
